export const onSelectSymbol = (symbol) => {
  symbol = symbol.replace("&", "_");
  window.open("https://in.tradingview.com/chart/?symbol=" + symbol, "_blank");
};

export const onSelectSymbolWatchList = (symbol, watchlist) => {
  if (watchlist === "Watch List 1") {
    symbol = symbols[symbol];
    window.open("https://in.tradingview.com/chart/?symbol=" + symbol, "_blank");
  } else {
    symbol = symbol.replace("&", "_");
    window.open("https://in.tradingview.com/chart/?symbol=" + symbol, "_blank");
  }
};

const symbols = {
  "NIFTY 50": "NIFTY",
  "NIFTY NEXT 50": "NIFTYJR",
  "NIFTY 100": "CNX100",
  "NIFTY 200": "CNX200",
  "NIFTY 500": "CNX500",
  "NIFTY MIDCAP 50": "NIFTYMIDCAP50",
  "NIFTY MIDCAP 100": "CNXMIDCAP",
  "NIFTY SMLCAP 100": "CNXSMALLCAP",
  "NIFTY MIDCAP 150": "NIFTYMIDCAP150",
  "NIFTY SMLCAP 50": "NIFTYSMLCAP50",
  "NIFTY SMLCAP 250": "NIFTYSMLCAP250",
  "NIFTY MIDSML 400": "NIFTYMIDSML400",
  "NIFTY500 MULTICAP": "NIFTY500_MULTICAP",
  "NIFTY LARGEMID250": "NIFTY_LARGEMID250",
  "NIFTY MID SELECT": "NIFTY_MID_SELECT",
  "NIFTY TOTAL MKT": "NIFTY_TOTAL_MKT",
  "NIFTY MICROCAP250": "NIFTY_MICROCAP250",
  "NIFTY BANK": "BANKNIFTY",
  "NIFTY AUTO": "CNXAUTO",
  "NIFTY FIN SERVICE": "CNXFINANCE",
  "NIFTY FINSRV25 50": "NIFTYFINSRV25_50",
  "NIFTY FMCG": "CNXFMCG",
  "NIFTY IT": "CNXIT",
  "NIFTY MEDIA": "CNXMEDIA",
  "NIFTY METAL": "CNXMETAL",
  "NIFTY PHARMA": "CNXPHARMA",
  "NIFTY PSU BANK": "CNXPSUBANK",
  "NIFTY PVT BANK": "NIFTYPVTBANK",
  "NIFTY REALTY": "CNXREALTY",
  "NIFTY HEALTHCARE": "NIFTY_HEALTHCARE",
  "NIFTY CONSR DURBL": "NIFTY_CONSR_DURBL",
  "NIFTY OIL AND GAS": "NIFTY_OIL_AND_GAS",
  "NIFTY DIV OPPS 50": "CNXDIVIDOPPT",
  "NIFTY GROWSECT 15": "NI15",
  "NIFTY100 QUALTY30": "NIFTYQUALITY30",
  "NIFTY50 VALUE 20": "NV20",
  "NIFTY50 TR 2X LEV": "NIFTYTR2XLEV",
  "NIFTY50 PR 2X LEV": "NIFTYPR2XLEV",
  "NIFTY50 TR 1X INV": "NIFTYTR1XINV",
  "NIFTY50 PR 1X INV": "NIFTYPR1XINV",
  "NIFTY ALPHA 50": "NIFTYALPHA50",
  "NIFTY50 EQL WGT": "NIFTY50EQUALWEIGHT",
  "NIFTY100 EQL WGT": "NIFTY100EQUALWEIGHT",
  "NIFTY100 LOWVOL30": "NIFTY100LOWVOL30",
  "NIFTY200 QUALTY30": "NIFTY200QUALTY30",
  "NIFTY ALPHALOWVOL": "NIFTYALPHALOWVOL",
  NIFTY200MOMENTM30: "NIFTY200MOMENTM30",
  "NIFTY M150 QLTY50": "NIFTY_M150_QLTY50",
  "NIFTY COMMODITIES": "CNXCOMMODITIES",
  "NIFTY CONSUMPTION": "CNXCONSUMPTION",
  "NIFTY CPSE": "CPSE",
  "NIFTY ENERGY": "CNXENERGY",
  "NIFTY INFRA": "CNXINFRA",
  "NIFTY100 LIQ 15": "LIX15",
  "NIFTY MID LIQ 15": "NIFTYMIDLIQ15",
  "NIFTY MNC": "CNXMNC",
  "NIFTY PSE": "CNXPSE",
  "NIFTY SERV SECTOR": "CNXSERVICE",
  NIFTY100ESGSECLDR: "NIFTY100ESGSECLDR",
  "NIFTY IND DIGITAL": "NIFTY_IND_DIGITAL",
  "NIFTY100 ESG": "NIFTY100_ESG",
  "NIFTY INDIA MFG": "NIFTY_INDIA_MFG",
  "NIFTY GS 8 13YR": "NIFTYGS8TO13YR",
  "NIFTY GS 10YR": "NIFTYGS10YR",
  "NIFTY GS 10YR CLN": "NIFTYGS10YRCLN",
  "NIFTY GS 4 8YR": "NIFTYGS4TO8YR",
  "NIFTY GS 11 15YR": "NIFTYGS11TO15YR",
  "NIFTY GS 15YRPLUS": "NIFTYGS15YRPLUS",
  "NIFTY GS COMPSITE": "NIFTYGSCOMPOSITE",
};
