export const data = {
  symbols_remaining: 0,
  symbols: [
    {
      symbol: "<em>AAR</em>TIIND",
      description: "<em>AAR</em>TI IND LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      logoid: "aarti-industries",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIDRUGS",
      description: "<em>AAR</em>TI DRUGS LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      logoid: "aarti-drugs",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>ON",
      description: "<em>AAR</em>ON INDUSTRIES LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>VI",
      description: "<em>AAR</em>VI ENCON LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TISURF",
      description: "<em>AAR</em>TI SURFACTANTS LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>NAV",
      description: "<em>AAR</em>NAV FASHIONS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>VEEDEN",
      description: "<em>AAR</em>VEE DENIMS & EX",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIPHARM",
      description: "<em>AAR</em>TI PHARMALABS LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIPP.E1",
      description: "<em>AAR</em>TI SURFACTANTS LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>EYDRUGS",
      description: "<em>AAR</em>EY DRUGS & PHARM LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TISURF.P1",
      description: "<em>AAR</em>TI SURFACTANTS LTD",
      type: "stock",
      exchange: "NSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["preferred"],
    },
    {
      symbol: "<em>AAR</em>TIDRUGS",
      description: "<em>AAR</em>TI DRUGS LTD.",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      logoid: "aarti-drugs",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIIND",
      description: "<em>AAR</em>TI INDUSTRIES LTD.",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      logoid: "aarti-industries",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIPHARM",
      description: "<em>AAR</em>TI PHARMALABS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TECH",
      description: "<em>AAR</em>TECH SOLONICS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TISURF",
      description: "<em>AAR</em>TI SURFACTANTS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TIPP",
      description: "<em>AAR</em>TI SURFACTANTS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>VEEDEN",
      description: "<em>AAR</em>VEE DENIMS & EXPORTS LTD.",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>TI_RE",
      description: "<em>AAR</em>TI SURFACTANTS LIMITED",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "AREYDRG",
      description: "<em>AAR</em>EY DRUGS & PHARMACEUTICALS",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      typespecs: ["common"],
    },
    {
      symbol: "<em>AAR</em>SHYAM",
      description: "<em>AAR</em> SHYAM INDIA INVESTMENT COM",
      type: "stock",
      exchange: "BSE",
      currency_code: "INR",
      provider_id: "ice",
      country: "IN",
      is_primary_listing: true,
      typespecs: ["common"],
    },
  ],
};
